<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\FlowRunFinderV2.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.2" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.2" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.2" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\FlowRunFinderV2.ico" />
    <None Include="Assets\FlowRunFinderV2.svg" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlowRunFinderV2.Core\FlowRunFinderV2.Core.csproj" />
  </ItemGroup>
</Project>
